### ISSUE TITLE
Implement full archive for Custom Photo Roster Photo View

### ISSUE THREAD

**Issue by amiedavis** [steveswinsburg/sakai-archiver#15]

**Comment by steveswinsburg** [comment]
Parked until I get direction on the approach to use

**Comment by steveswinsburg** [comment]
This will be a custom archiver provider using the Yale libraries provided.

**Comment by steveswinsburg** [comment]
This is done in m3. The demo environment uses a hardcoded photo for all students due to the mock services. It currently puts the data into its own custom directory but that will be eventually put into the main roster archive directory. The way this is written it should just work when wired up with the real environment.
