### ISSUE TITLE
Additional screen in admin tool that shows who performed archives

### ISSUE THREAD

**Issue by amiedavis** [steveswinsburg/sakai-archiver#31]

**Comment by steveswinsburg** [comment]
Create report screen only visible to admin.

Show last 100 archives across every site.

Allow selecting a site and can see all for that site.

**Comment by steveswinsburg** [comment]
The admin screen and main instructor screen are currently the same. I can add an additional column to this table to add site title and archiver name.

**Comment by steveswinsburg** [comment]
![screen shot 2017-08-01 at 8 03 17 pm](https://user-images.githubusercontent.com/129129/28824444-49787f22-7705-11e7-9df6-c6fc97b37286.png)

Done for m7.

**Comment by steveswinsburg** [comment]
This is done. Admin user can now search for a site to show the archives made in that site.

**Comment by cacostantino** [comment]
I did a search for "russ" but the screen remained the same with the full list.
<img width="596" alt="image" src="https://user-images.githubusercontent.com/29150601/30559115-88f7c184-9c81-11e7-9cb2-a270ba9e4f4b.png">

**Comment by steveswinsburg** [comment]
It is case sensitive. I'll change that to ignore case.

**Comment by steveswinsburg** [comment]
Actually this is a limitation of the Sakai API. In order to make this case insensitive it would have to be three searches instead of one. One in original case, one all lower, one all upper. In the interest of time and performance I am going to leave this as is. The line of code where this could be modified is:
https://github.com/steveswinsburg/sakai-archiver/blob/c7f1f177017c227aee5d21d383d69f13041e26db/tool/src/java/org/sakaiproject/archiver/app/business/ArchiverBusinessService.java#L261
