### ISSUE TITLE
Identify alternatives to .json file format

### ISSUE THREAD

**Issue by dah36** [steveswinsburg/sakai-archiver#54]
Faculty will be intimidated by .json tags. Our preference would be to have .json files rendered as basic HTML or simple text without tags

**Comment by steveswinsburg** [comment]
I'm looking into this and may have a solution soon.

Note that a lot of the data is configuration data, ie the settings for an announcement or the metadata about something and is raw data direct from the API objects with the field names emitted as is. 

Also, where something contains HTML as part of the configuration (ie the announcement message), this has the potential to break the display of the HTML file. 

In addition, if it is HTML rather than a data format, users may expect links between the HTML files which would require significant additional processing and might not even be doable.

I am wondering if it might be best to just have the ability to view the JSON data in a better manner? ie https://jsonview.com/

**Comment by steveswinsburg** [comment]
I've put in a first cut of a HTML representation. I'll get this onto the demo server so you can take a look.

Would it be worthwhile having the option of choosing HTML or JSON as the output format?

**Comment by dah36** [comment]
We don't see any benefit to end users (faculty) to having a JSON option, so HTML alone would be fine.  Plus it keeps things simple for faculty not to have to choose.

**Comment by steveswinsburg** [comment]
JSON has largely been removed from the latest build and HTML is there for pretty much everything. This is the first cut at a HTML representation of the data. If it needs to be enhanced it can be, but each tool's archiver will require a little bit of work.
