### ISSUE TITLE
Assignments: HTML layout

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#86]
The HTML document should look more like the UI version below. With the addition of the Assignment title at the Top. The Modified by Instructor line in red is NOT needed.

Assignment 1
<img width="827" alt="image" src="https://user-images.githubusercontent.com/29150601/27748280-d2bebe36-5d9c-11e7-93ff-bf51b3c26e2b.png">

**Comment by cacostantino** [comment]
Priority: MEDIUM

**Comment by steveswinsburg** [comment]
@amiedavis could you please have a look at restructuring the HTML for assignments? Thanks.

**Comment by steveswinsburg** [comment]
@cacostantino this is going to be time consuming to implement as we only have access to the data objects and their parameter names rather than the translated values (ie startDate vs open). It can be done but will take a fair amount of time to do as it will be a custom HTML rendering. CAn you let me know if this is required?

@amiedavis can you remove the 'Modified by instructor' field please?

**Comment by cacostantino** [comment]
@steveswinsburg Let's cancel this one. David and I are looking at the HTML layout of all the tools most holistically and will submit a different ticket.
